version: "3.0"
# name: canlytics

services:
  server:
    # image: 228301419483.dkr.ecr.eu-west-2.amazonaws.com/canlytics-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u app.py
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis
    #   - mongodb
    #   - influxdb
    # environment:
    #   - env=PROD
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=vehicleDiagnostics
      - DOCKER_INFLUXDB_INIT_ORG=pdsl
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=user@123
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - influxdb:/var/lib/influxdb

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: python -u worker.py
  #   depends_on:
  #     - redis
  #     - mongodb
  #     - influxdb
  #   volumes:
  #     - .:/app


volumes:
  influxdb:
  mongodb:
  redis: